@startuml
OkHttpClient -> RealCall:newRealCall
activate RealCall

RealCall -> RealCall:execute
RealCall -> RealInterceptorChain:proceed
RealInterceptorChain -> XXXInterceptor:intercept
XXXInterceptor -> RealInterceptorChain:proceed
RealInterceptorChain -> CallServerInterceptor:intercept
CallServerInterceptor -> Response
RealInterceptorChain <-- Response
XXXInterceptor <-- RealInterceptorChain
RealCall <-- XXXInterceptor

deactivate RealCall
@enduml